### PR TITLE
Add installation package imageoptimizer

### PR DESCRIPTION
**Pull request by bambycha**
Related with Railsreactor/realestateapp-backend/pull/92.

### CODE REVIEW

**Comment by dmishh** [comment]
All is good except `bundler` is a bit outdated

**Comment by bambycha** [comment]
Is the newest version 1.99.99?

**Comment by rilian** [comment]
good

**Comment by dmishh** [comment]
❯ bundle --version                                                                                                                                 
Bundler version 1.10.6

**Pull request merged**
