### PR TITLE
Always copy config files for automatic security upgrades

### PR DESCRIPTION
**Pull request by dmishh**

### CODE REVIEW

**Comment by rilian** [comment]
?

**Comment by dmishh** [comment]
Ubuntu has them by default with it's own settings. So there are two ways how to fix current code: check that configs are identical with the remotes (in verify) or always copy them.

**Comment by rilian** [comment]
i just do not understand how removal of verification fixes the problem

**Comment by dmishh** [comment]
If `verify` returns true, nothing happening. So in the existing code if files exist, they will not be copied second time.

**Comment by rilian** [comment]
ok

**Pull request merged**
